### PR TITLE
Fix stale host map when ingress is deleted

### LINKED ISSUE #674: Expire all relevant k8s config source cache data
We currently only expire `appMap` in k8s config source, we should also expire entries in `hostMap`, etc.

### PR DESCRIPTION
**Pull request by louischan-oursky**
fix #674

### CODE REVIEW

File: pkg/lib/config/configsource/kubernetes.go [hunk 1]
```diff
@@ -155,7 +156,13 @@ func (k *Kubernetes) invalidateHostMap(ingress *networkingv1beta1.Ingress) {
 }
 
 func (k *Kubernetes) updateHostMap(appID string, ingress *networkingv1beta1.Ingress) {
-	for _, host := range extractIngressHosts(ingress) {
+	hosts := extractIngressHosts(ingress)
+
+	k.ingressMap.Store(ingress.UID, &ingressSnapshot{
```
Comment (kiootic) [inline pkg/lib/config/configsource/kubernetes.go:161]: We should delete the previous hosts, for example, when ingress hosts are updated from `["test1.localhost"]` to `["test2.localhost"]`, `test1.localhost` should be deleted.

Comment (louischan-oursky) [reply pkg/lib/config/configsource/kubernetes.go:170]: fixed.

**Review by kiootic — APPROVED** [review]
