### PR TITLE
Fix not preserving OAuth parameter at internal links

### LINKED ISSUE #123: Cannot use alternative links when logging in through OAuth with existing session
When logging in through OAuth(prompt=login) with existing session, alternative links (e.g. use phone instead, create account) would lead to settings page. This is due to the OAuth parameters are not propagated in these links.

### PR DESCRIPTION
**Pull request by kiootic**
fix #123

### CODE REVIEW

File: pkg/auth/dependency/webapp/url_provider.go [hunk 1]
```diff
@@ -86,38 +84,39 @@ type AuthenticateURLProvider struct {
...
-		q["prompt"] = options.Prompt
-	}
-	if options.UILocales != "" {
-		q["ui_locales"] = options.UILocales
+	inputer := func() (interface{}, error) {
+		return nil, nil
 	}
+
+	intent.RedirectURI = options.RedirectURI
+	intent.UILocales = options.UILocales
```
Comment (louischan-oursky) [inline pkg/auth/dependency/webapp/url_provider.go:98]: These two lines seem redundant. We have set the two fields when intent is constructed at line 87.

Comment (kiootic) [reply pkg/auth/dependency/webapp/url_provider.go:98]: oops forgot to delete them when moving them up...
