### PR TITLE
Handle more create app errors

### LINKED ISSUE #781: [Portal, Create App] Error message for invalid app ID can be more specific
## Background:
- Device / Browser (OS version): Safari on Mac OS
- Build: Staging - 23-11-2020

## Description:
In create a new App page. On the App ID field, when I input the app ID mix with any capital letter. Will show a message "Failed to create app " and "Error: invalid app ID". 
     
## Steps to reproduce:
1. After login into the Auth Gear portal https://portal.authgear-staging.com/apps
2. On the portal page, Click "Create App". 
3. In App ID field input "FFsks".
4. After click the "Create" button.
5. The error message will show up. 

## Expected result:
The Message show be more specifically to the problem. For example. "The App ID is not allow any capital letter."

## Screenshot:
Screenshot_2020-11-23_at_3.32.35_PM

### PR DESCRIPTION
**Pull request by carmenlau**
fix #781

### CODE REVIEW

File: portal/src/error/apps.ts [hunk 1]
```diff
@@ -2,3 +2,13 @@ export interface APIDuplicatedAppIDError {
...
   reason: "DuplicatedAppID";
 }
+
+export interface APIReservedAppIDError {
+  errorName: "Forbidden";
+  reason: "AppIDReserved";
+}
+
+export interface APIInvalidAppIDError {
+  errorName: "Invalid";
```
Comment (kiootic) [inline portal/src/error/apps.ts:12]: The invalid app ID error is currently a generic error (i.e. `apierrors.NewInvalid`) produced by `AppService`. Since we need to interpret the error programmatically now, we should assign a correct reason (e.g. `InvalidAppID`) at server side like the reserved app ID error above.

**Review by kiootic — APPROVED** [review]
