### PR TITLE
Fix inconsistent masking of phone number

### LINKED ISSUE #643: [Demo App] Inconsistent masking for phone no. on SMS OTP and 2-step verification pages
## Environment:
- Platform: Web / Android / iOS
- Demo app build: Android 1.0 (1602057818), iOS 1.0 (1602057811)

## Description:
Inputted phone no. is masked only on the SMS 2-step verification page, but not on other phone no. verification pages.

## Steps to reproduce:
1. Log in to the login gateway of any app entity
2. Go to the 'Connected identity' > 'Change phone no.' > proceed with any valid phone no.
3. See the phone no. is not masked
4. Go to the 'Verification code via SMS / Email' > 'Add' > 'Setup SMS 2-step verification instead' > Proceed with any valid phone no.
5. See the phone no. here is masked

## Expected result:
Should have a consistent display of the phone no. inputted

## Screenshot:
image
image

### PR DESCRIPTION
**Pull request by axolotl0212**
fix #643 

Mask phone number for change phone number verification screen
such that it is consistent with screen for verify phone number for
adding secondary sms authenticator

# Screenshot

Screenshot 2020-11-02 at 3 11 17 PM

Screenshot 2020-11-02 at 4 48 02 PM

### CODE REVIEW

File: pkg/auth/handler/webapp/verify_identity.go [hunk 1]
```diff
@@ -78,10 +80,16 @@ func (h *VerifyIdentityHandler) GetData(r *http.Request, state *webapp.State, gr
...
-		viewModel.IdentityDisplayID = n.GetVerificationIdentity().DisplayID()
+		rawIdentityDisplayID := n.GetVerificationIdentity().DisplayID()
 		viewModel.VerificationCodeSendCooldown = n.GetVerificationCodeSendCooldown()
 		viewModel.VerificationCodeLength = n.GetVerificationCodeLength()
 		viewModel.VerificationCodeChannel = n.GetVerificationCodeChannel()
+		switch authn.AuthenticatorOOBChannel(viewModel.VerificationCodeChannel) {
+		case authn.AuthenticatorOOBChannelSMS:
+			viewModel.IdentityDisplayID = phone.Mask(rawIdentityDisplayID)
+		default:
+			viewModel.IdentityDisplayID = rawIdentityDisplayID
```
Comment (kiootic) [inline pkg/auth/handler/webapp/verify_identity.go:91]: We also mask emails using `mail.MaskAddress`.

Comment (axolotl0212) [reply pkg/auth/handler/webapp/verify_identity.go:91]: OK, will add the corresponding mask as well

**Comment by axolotl0212** [comment]
@kiootic updated and rebased

**Review by kiootic — APPROVED** [review]
