### PR TITLE
Disallow navigate to same page

### LINKED ISSUE #427: [Portal] Erroneous confirmation dialog on navigation to same page
When form is modified and the same tab is selected in the nav bar, a confirmation dialog would appear but 'Confirm' button is not working.

### PR DESCRIPTION
**Pull request by axolotl0212**
fix #427

### CODE REVIEW

File: portal/src/ScreenNav.tsx [hunk 1]
```diff
@@ -2,6 +2,25 @@ import React, { useMemo, useCallback, useContext } from "react";
...
+  // app router -> /app/:appID/*
+  // discard first 3 segment (include leading slash)
+  return location.pathname.split("/").slice(3).join("/");
+}
+
+function getPath(url: string) {
+  // remove leading trailing slash, remove fragment
+  const regexpMatch = /^\/?([^#]*[^/#])\/?(#.*)?$/.exec(url);
+  return regexpMatch ? regexpMatch[1] : null;
+}
```
[the remark this answers is not in the document]
Comment (louischan-oursky) [reply portal/src/ScreenNav.tsx:17]: We should use the URL constructor directly.

[the remark this answers is not in the document]
Comment (axolotl0212) [reply portal/src/ScreenNav.tsx:17]: Tried using URL constructor, but it does not solve the leading / trailing slash inconsistency, take the example

```javascript
new URL("about:"+"/abc/def#123").pathname = "/abc/def"
new URL("about:"+"/abc/def/#123").pathname = "/abc/def/"
new URL("about:"+"abc/def#123").pathname = "abc/def"
```

[the remark this answers is not in the document]
Comment (louischan-oursky) [reply portal/src/ScreenNav.tsx:17]: I mean you should use URL constructor to convert a string to an instance of URL, and then use the pathname property to get the path, after that, apply your remove-trailing-slash logic on pathname.

**Comment by axolotl0212** [comment]
@louischan-oursky updated and rebased

File: portal/src/ScreenNav.tsx [hunk 2]
```diff
@@ -2,6 +2,27 @@ import React, { useMemo, useCallback, useContext } from "react";
...
+  // app router -> /app/:appID/*
+  // discard first 3 segment (include leading slash)
+  return location.pathname.split("/").slice(3).join("/");
+}
+
+function getPath(url: string) {
+  // remove fragment
+  const path = new URL("scheme:" + url).pathname;
+  // remove leading trailing slash
+  const regexpMatch = /^\/?(.*[^/])\/?$/.exec(path);
```
Comment (louischan-oursky) [inline portal/src/ScreenNav.tsx:17]: `/^\/?(.*[^/])\/?$/.exec("/")` is null.

I would write

```typescript
// "/" would become empty string
// Is this result we are expecting?
const pathWithoutLeadingTrailingSlash = path.replace(/^\//, "").replace(/\/$/, "")
```

Comment (axolotl0212) [reply portal/src/ScreenNav.tsx:17]: > "/" would become empty string
Is this result we are expecting?

I think we won't have "/" in navigation bar item, and removing slash is for consistency in comparison, so I think "/" becomes empty string is OK (it will work even if the path is "/"). 

> const pathWithoutLeadingTrailingSlash = path.replace(/^\//, "").replace(/\/$/, "")

This looks much nicer

**Comment by axolotl0212** [comment]
updated

File: portal/src/hook/usePivot.ts [hunk 3]
```diff
@@ -1,24 +1,28 @@
...
   const location = useLocation();
   const hash = location.hash.slice(1);
 
   const onLinkClick = useCallback(
-    (item) => {
+    (item?: { props: IPivotItemProps }) => {
       const itemKey = item?.props.itemKey;
       if (typeof itemKey === "string") {
-        navigate(`./#${encodeURIComponent(itemKey)}`);
+        if (itemKey !== pivotRef.current?.state.selectedKey) {
```
Comment (louischan-oursky) [inline portal/src/hook/usePivot.ts:19]: So the `selectedKey` from the argument is different from `pivotRef.current?.state.selectedKey`?  The `ref.state.selectedKey` seems very hacky to me. It looks like accessing the internal state of the Pivot.

Comment (axolotl0212) [reply portal/src/hook/usePivot.ts:19]: > So the selectedKey from the argument is different from pivotRef.current?.state.selectedKey?

Yes, when we click cancel in navigation blocker dialog, `selectedKey` state is updated (unexpected) even if hash (`selectedKey` from the argument) stays the same, and the `PivotItem` is unchanged as well (expected)

> It looks like accessing the internal state of the Pivot.

It is the internal state of Pivot. But I am not sure why the internal state does not match with the blue underline style and the rendered PivotItem

**Comment by axolotl0212** [comment]
Re-written the first commit to solve the problem @louischan-oursky

**Review by nicolaslee2775 — APPROVED** [review]
