### PR TITLE
Fix accessibility issues

### LINKED ISSUE #276: [Portal] Fix existing accessible issues
We can view them in the console

### LINKED ISSUE #281: [Portal] Fix inconsistent fonts
The rendered font for elements is inconsistent, especially the headers. Some are rendered `Segoe UI`, some are `.SF NS`. I suggest using `Text` component of Fluent UI at all time to ensure consistent styling.

### PR DESCRIPTION
**Pull request by axolotl0212**
Closes #276
Closes #281 

add aria label
use label in fluent UI if possible
fix inconsistent font

### CODE REVIEW

File: portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx [hunk 1]
```diff
@@ -46,16 +46,17 @@ const switchStyle = { root: { margin: "0" } };
 const WidgetHeader: React.FC<WidgetHeaderProps> = function (
   props: WidgetHeaderProps
 ) {
+  const { renderToString } = React.useContext(Context);
+
   return (
     <div className={styles.widgetHeader}>
       <Toggle
+        label={renderToString(props.titleId)}
```
Comment (louischan-oursky) [inline portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx:54]: Can it accept `<FormattedMessage>`?

File: portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx [hunk 2]
```diff
@@ -285,6 +286,7 @@ const AuthenticationLoginIDSettings: React.FC<Props> = function AuthenticationLo
           initiallyExtended={usernameEnabled}
           extendable={true}
           readOnly={!usernameEnabled}
+          extendButtonAriaLabelId={"AuthenticationWidget.usernameExtend"}
```
Comment (louischan-oursky) [inline portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx:289]: Since this component is owned by us, we can make it to support `ariaLabel: React.ReactNode`. Then we can pass it `<FormattedMessage>`

File: portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx [hunk 3]
```diff
@@ -304,6 +306,7 @@ const AuthenticationLoginIDSettings: React.FC<Props> = function AuthenticationLo
             />
 
             <CheckboxWithContent
+              ariaLabel={renderToString("AuthenticationWidget.excludeKeywords")}
```
Comment (louischan-oursky) [inline portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx:309]: `ariaLabel: React.ReactNode`

**Review by louischan-oursky — COMMENTED** [review]
Maybe we can fix #281 in this PR as well.

File: portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx (hunk 1 above)
Comment (axolotl0212) [reply portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx:54]: Just found out that toggle label can accept JSX.Element, will update this

File: portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx (hunk 2 above)
Comment (axolotl0212) [reply portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx:289]: However we need to pass the props to `IconButton` in fluentUI. The ariaLabel in `IconButton` must be string. @louischan-oursky

File: portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx (hunk 3 above)
Comment (axolotl0212) [reply portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx:309]: `ariaLabel` in `Checkbox` component in fluent UI also only takes string

File: portal/src/DetailsListWithOrdering.tsx [hunk 4]
```diff
@@ -25,36 +26,49 @@ interface OrderColumnButtonsProps {
...
+    if (index == null) {
       return;
     }
-    props.onSwapClicked(props.index, props.index + 1);
-  }, [props]);
+    onSwapClicked(index, index + 1);
+  }, [index, onSwapClicked]);
+
+  const ariaLabelUp = React.useMemo(() => {
+    return [renderAriaLabel(index), renderToString("up")].join(" | ");
```
Comment (kiootic) [inline portal/src/DetailsListWithOrdering.tsx:51]: I would suggest making it localized. Also, since this label may be used by screen readers, using a complete readable phrase seems better.
Maybe something like "Move {key} up"/"Move {key} down"?

Comment (axolotl0212) [reply portal/src/DetailsListWithOrdering.tsx]: Pushed 1 more commit to update the label. The label is `Move {key} up` and {key} is rendered by function provided by user of the component

File: portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx (hunk 2 above)
Comment (louischan-oursky) [reply portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx:287]: Fair enough.

File: portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx (hunk 3 above)
Comment (louischan-oursky) [reply portal/src/graphql/portal/AuthenticationLoginIDSettings.tsx:307]: Fair enough.

**Comment by axolotl0212** [comment]
@louischan-oursky Fixed the font family mismatch I can found

**Comment by axolotl0212** [comment]
Just saw this comment (https://github.com/authgear/authgear-server/issues/281#issuecomment-690843454). Turned on lint rule to ban h1, h2

File: portal/.eslintrc.json [hunk 5]
```diff
@@ -17,6 +17,7 @@
   "globals": { "Set": "readonly" },
   "rules": {
     "react/jsx-no-bind": "off",
+    "react/forbid-elements": [1, { "forbid": ["h1", "h2"] }],
```
Comment (kiootic) [inline portal/.eslintrc.json:20]: Please also ban h3 - h6.

Comment (axolotl0212) [reply portal/.eslintrc.json]: updated commit

**Review by kiootic — APPROVED** [review]
